### PR TITLE
Syntax and CSS Fixes

### PR DESCRIPTION
**Pull request by convenient**
I've fixed quite a few invalid `html` things, such as closing tags not matching and not having a `<html>` tag for one. Each commit should be sufficient for explanation.

I've also been moving the `style="blah:69px"` that peppered the code into a stylesheet.

By doing this cleanup, any transition into making a proper mobile bootstrap website should be approx 145% easier.

I've attempted to keep the site looking identical, but there are minor variations. Nothing to worry about though.

### CODE REVIEW

**Comment by convenient** [comment]
Ahh I see you've changed around the index.html...

Need help managing the conflict?

**Comment by njall** [comment]
Ooof, I'll go through it manually. I only changed the very top jumbotron so it won't be too hard. Thanks for all the help :) It's looking pretty fly

**Comment by njall** [comment]
I kept my header as I've switched it to a  table format that scales nicely. Your float:right went a bit funny on smaller viewports. The rest is great though

**Comment by convenient** [comment]
Fair enough with the header. However, using tables for layout stopped being common practice sometime in the early 00's.

http://stackoverflow.com/a/84986/4354325

If there's an appetite for making this bootstrap do its mobile thing then the following really needs to happen:
-  Replace all the inline `style=` with css
-  Refactor the results section, it's got quite a confusing nest of tables within tables. This won't play well on anything with a smaller screen.
-  Refactor out pretty much all of the `<br>` tags. In the refactor merge you can see that these are managed in `css` using `margin-top` or `margin-bottom`.

**Pull request merged**
